# -*- coding: utf-8 -*-
"""process Quiz1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14dnaPuEmTZsaWGhD5ai-8W2iyJdNCipN

Required Library:

 It imports keras, several layers (Dense, Dropout, Conv2D, etc.), image preprocessing, and Sequential (for model development).
 Additionally, matplotlib.pyplot and cifar10 from keras.datasets are imported for visualization.

 Activate the CIFAR-10 Dataset:

 Utilizing cifar10.load_data(), the dataset is loaded, yielding x_train, y_train, x_test, and y_test.

 Configuration parameters set:

 Num_classes = 10 specifies the number of classes.
 looks over the dataset to find the input_shape.
 sets up the optimizer (Adam) with a 0.001 learning rate.

 One-Hot Encoding Conversion for Labels:

 They use keras.utils.to_categorical() to translate the labels (y_train and y_test).

 Visualize a Dataset Sample Image:

 To show an example image, use plt.imshow(x_train[1]).
 The image's shape (x_train[1].shape) is printed.

Import Libraries:

Necessary libraries for deep learning and image processing are imported.

Extract Data and Split into Train and Test Sets:

The dataset is loaded and divided into training and testing sets.

Visualize Dataset Images:

The dataset images are displayed to understand their structure.

Train, Validate, and Split Data:

The training and testing datasets are further split for validation.

Use a CNN Model with 16 Layers:

A convolutional neural network (CNN) is implemented with 16 layers (out of 19 available).
"""